### ISSUE TITLE
对于项目的疑问

### ISSUE THREAD

**Issue by Pantheooon** [banq/jivejdon#12]
老哥,你这代码,ddl语句没有注释,啥意思全靠猜,代码也没有注释,这样的项目用了ddd也可以很容易维护吗?

**Comment by banq** [comment]
非常抱歉，精力有限，可先阅读文档：https://www.jdon.com/ddd/jivejdon/1.html 更详细的领域模型设计解说见出版书籍，DDD软件主要看领域模型是如何设计的。
