### ISSUE TITLE
登录报这个错误

### ISSUE THREAD

**Issue by orangeyts** [banq/jivejdon#2]
![image](https://user-images.githubusercontent.com/4250869/45343267-0156e900-b5d3-11e8-926a-abfc780b447c.png)

需要哪里修改一下？

**Comment by banq** [comment]
应该没事，如果本地不能访问，进行管理http://localhost:8080/admin/ ， 查询查封IP，把127.0.0.1删除即可

**Comment by orangeyts** [comment]
是改web.xml 下面的配置？

`

				<param-value>.*(https://www.jdon.com|http://www.jdon.com|http://10.0.2.2|http://110.76.43.83).*</param-value>
			</init-param>
	
`

**Comment by banq** [comment]
<param-value>.*(http://127.0.0.1|http://localhost|https://www.jdon.com|http://www.jdon.com).*</param-value>
默认的127.0.0.1已经在里面，可以加入你的IP或域名，看你是使用域名访问还是IP访问

**Comment by banq** [comment]
登录报错是因为错误密码反复登录，用管理密码登录一下admin/admin 这样能了解tomcat的权限配置是否正确

**Comment by orangeyts** [comment]
启动日志发现了这个
![image](https://user-images.githubusercontent.com/4250869/45360378-f8c9d700-b601-11e8-90f9-15cfa1270386.png)

忘记 jaas.jar放入tomcat/lib了 <‘/\’>

现在可以登录了，但是也没都是400

![image](https://user-images.githubusercontent.com/4250869/45360622-b0f77f80-b602-11e8-8209-223d20c9601c.png)

后台也没有任何异常日志

![image](https://user-images.githubusercontent.com/4250869/45360642-c076c880-b602-11e8-8867-cf7a3f089e5b.png)

![image](https://user-images.githubusercontent.com/4250869/45360667-e13f1e00-b602-11e8-9e86-2b8b95dc495e.png)

**Comment by banq** [comment]
400错误可能因为之前refer设置限制，直接在web.xml中取消下面行
```
直接失效这个功能，在web.xml中去除下面：
<filter-mapping>
			<filter-name>spamFilterRefer</filter-name>
			<url-pattern>*.shtml</url-pattern>
		</filter-mapping>
		<filter-mapping>
			<filter-name>spamFilterRefer</filter-name>
			<url-pattern>*.jsp</url-pattern>
		</filter-mapping>

		<!--  spamFilterTooFreq -->
		<filter-mapping>
			<filter-name>spamFilterTooFreq</filter-name>
			<url-pattern>*.shtml</url-pattern>
		</filter-mapping>			
			
```

**Comment by orangeyts** [comment]
谢谢，可以访问了
![image](https://user-images.githubusercontent.com/4250869/45402643-40477600-b689-11e8-9808-1a83b6dbc27e.png)
