### ISSUE TITLE
部分依赖缺失

### ISSUE THREAD

**Issue by Roronoaliang** [banq/jivejdon#7]
com.jdon:jdon-jdbcTemp:jar:6.6.4	
com.jdon:jdon-struts1x:jar:6.6.4	
com.jdon:jdon-treepattern:jar:6.6.4	
com.jdon:jdonaccessory:jar:6.6.4	
tecentweibo:tecentweibo:jar:6.6.4	
weibo4j:weibo4j:jar:6.6.4	
log4j2.jar
以上依赖都下载不了，mvnrepository上也搜索不到这些依赖

**Comment by banq** [comment]
配置maven仓库 :

 <repositories>

        <repository>
            <id>jdon-struts1x</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>jdonaccessory</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>jdon-jdbcTemp</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>jdon-treepattern</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>weibo4j</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>tecentweibo</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>compass</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>lucene</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>urlrewrite</id>
            <url>https://github.com/banq/jdon-mvn-repo/raw/master/releases</url>
        </repository>
    </repositories>
